BLSQ/bluesquare-components

- dist/components/table/Table/Head.js
- dist/components/table/Table/HeadCell.js
- dist/components/table/Table/index.js
- src/components/table/Table/Head.js
- src/components/table/Table/HeadCell.js
- src/components/table/Table/index.js
Press alt key on your keyboard while sorting a column.
> IA-749:  TABLE multi sort

- dist/components/table/Table/index.js
- src/components/table/Table/index.js
- put back default sorted
- better handling sort change (avoid useEffect)
> IA-767: When going to the form table we do a double query to the frontend

- dist/components/inputs/Select/index.js
- src/components/inputs/Select/index.js
- passed `disabled` prop to `AutoComplete`
> IA-797 Select can be disabled

- dist/components/table/Table/PageSelect.js
- dist/components/table/Table/Pagination.js
- src/components/table/Table/PageSelect.js
- src/components/table/Table/Pagination.js
- When typing a page number, the search is only performed after `Enter` has been pressed
- The `SelectPage` input size will adapt to the length of the value input (up to 7 digits)
https://user-images.githubusercontent.com/38907762/134704545-b1f9588d-02e9-4e8a-810f-02132d45ae0d.mov
> IA-759 fix TablePagination

- src/utils/intlUtils.js
- Added a hook to translate dropdown list options and avoid passing `formatMessage`everytime
> POLIO-102: add useTranslatedOptions hook

- dist/components/DatePicker/index.js
- dist/components/inputs/Select/index.js
- dist/components/inputs/styles.js
- src/components/DatePicker/index.js
- src/components/inputs/Select/index.js
- src/components/inputs/styles.js
> IA-803: normalise end adornment

- src/components/table/Table/tableUtils.js
- src/utils/tableUtils.js
Fix application of filter default value in table params
> IA-879 Fix default search in children tab

- dist/components/table/Table/TablePaginationActions.js
- src/components/table/Table/TablePaginationActions.js
> Move pagination if result to bottom on table component

- dist/components/Treeview/DynamicSelect.js
- dist/components/Treeview/EnrichedTreeItem.js
- dist/components/Treeview/IasoTreeView.js
- dist/components/Treeview/TreeViewResultsCountSelect.js
- dist/components/Treeview/TreeViewWithSearch.js
- dist/components/Treeview/TruncatedTreeview.js
- dist/components/Treeview/messages.js
- dist/components/Treeview/requests.js
- dist/components/Treeview/utils.js
- dist/index.js
- dist/locale/en.json
- dist/locale/fr.json
- package-lock.json
- package.json
- src/components/Treeview/DynamicSelect.js
- src/components/Treeview/EnrichedTreeItem.js
- src/components/Treeview/IasoTreeView.js
- src/components/Treeview/TreeViewResultsCountSelect.js
- src/components/Treeview/TreeViewWithSearch.js
- src/components/Treeview/TruncatedTreeview.js
- src/components/Treeview/messages.js
- src/components/Treeview/requests.js
- src/components/Treeview/utils.js
- src/index.js
- src/locale/en.json
- src/locale/fr.json
- Added the Treeview and removed Iaso code
-  Did not add the modal, as it was tailored to the `OrgUnits` api
-  Same with the `Select`-like `OrgUnitTreeviewPicker`
> Add Treeview

- dist/components/inputs/SearchInput/index.js
- src/components/inputs/SearchInput/index.js
> IA-1042 add error to Search

- dist/components/table/Table/Count.js
- dist/components/table/Table/TablePaginationActions.js
- src/components/table/Table/Count.js
- src/components/table/Table/TablePaginationActions.js
Put `'pagination-count'` className directly on the `Count` component so tests won't fail when `countOnTop` is true
> patch: move test className for Count

- dist/components/Treeview/EnrichedTreeItem.js
- dist/components/Treeview/IasoTreeView.js
- dist/components/Treeview/requests.js
- src/components/Treeview/EnrichedTreeItem.js
- src/components/Treeview/IasoTreeView.js
- src/components/Treeview/requests.js
- add optional queryOptions and childrenQueryOptions props
- set retry to false by default in Treeview requests
> fix: enable passing options to TV useQuery

- .gitignore
- dist/components/Treeview/TreeViewWithSearch.js
- dist/components/Treeview/TruncatedTreeview.js
- src/components/Treeview/TreeViewWithSearch.js
- src/components/Treeview/TruncatedTreeview.js
- replaced `onClick` prop from `TruncatedTreeview` with `redirect`
- `redirect` will be called onLabelClick and passed the `key` of the map item used to render the `TreeviewItem`
-  `redirect`will not be called if the mouse button is held long enough, preserving the ability to select and copy the text displayed
> IA-1084: redirect from truncated tree view

- dist/styles/iaso/theme.js
- src/styles/iaso/theme.js
> IA-1128: change theme colors

- dist/components/inputs/Select/index.js
- src/components/inputs/Select/index.js
- removed `touched`prop from `Select` as it prevented the component from entering error state
> Remove unused prop from Select component

- src/components/buttons/AddButton/index.js
Add of a dataTestId prop to the component to target it in tests
> adding dataTestId prop to AddButtonComponent

- dist/components/buttons/AddButton/index.js
- src/components/buttons/AddButton/index.js
> Ia 1177 add data test props

- dist/components/buttons/IconButton/index.js
- src/components/buttons/IconButton/index.js
added prop so we can use `data-test`as selector in cypress test
> fix: add dataTestId prop to IconButtonComponent

- dist/components/LoadingSpinner/index.js
- dist/utils/fetchData.js
- src/utils/fetchData.js
CreateUrl was not working with zero as a value
> IA-1234: version 0

- package-lock.json
- package.json
Force html-entities version to avoid:
> Fix hot reload

- dist/locale/en.json
- dist/locale/fr.json
- src/components/inputs/Select/messages.js
- src/components/inputs/Select/multi.js
- src/components/inputs/Select/single.js
- src/locale/en.json
- src/locale/fr.json
Add translation for loading text when fetching options in a Select
> IA-1507: select input loading state not translated
